# Generated by Django 3.0.3 on 2020-06-24 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hotel_detail',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rev_stars',
            field=models.IntegerField(max_length=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=512, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
